# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
